on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Push Wiki Folder to Repo
            uses: docker://decathlon/wiki-page-creator-action:latest
            env:
                ACTION_MAIL: joeizzard@users.noreply.github.com
                ACTION_NAME: joeizzard
                GH_PAT: ${{ secrets.GH_PAT }}
                MD_FOLDER: wiki
                OWNER: joeizzard
                REPO_NAME: .github